### ISSUE TITLE
Incorrect assignment of "this"

### ISSUE THREAD

**Issue by shitcricket** [6to5/6to5#560] opened 2015-01-21 16:24 UTC
Consider the following input:

```js
// File 'x.es'
'use strict';

module.exports = {
    x: 'X',
    getX: () => {
      return this.x;
    }
};
```

which gets compiled to:

```js
// File 'x.js'
"use strict";

var _this = this;
module.exports = {
  x: "X",
  getX: function () {
    return _this.x;
  }
};
```

Which results in the following, incorrect behaviour:
```js
var m = require('x')
console.info(m.getX()); // outputs "undefined'
```

The reason obviously being that `this` does not point to the exported object but the module scope.

**Comment by fkling** [comment] 2015-01-21 16:25
That is to be expect. Arrow functions bind to the `this` of the environment.

**Comment by shitcricket** [comment] 2015-01-21 16:31
Interestingly, it works just fine in io.js

Maybe I should open an issue there then.

**Comment by fkling** [comment] 2015-01-21 16:34
Mmh. Either that or there is a special behavior for arrow functions at the top level. But I doubt that...

**Comment by fkling** [comment] 2015-01-21 16:58
After some more digging, I think that io.js is incorrect. From the spec:

https://people.mozilla.org/~jorendorff/es6-draft.html#sec-function-environment-records
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-getthisenvironment

**Comment by fkling** [comment] 2015-01-21 17:33
So, the wait I referred to is not actually relevant to the issue. I think neither io.js nor 6to5 is to blame here.

We already established that the `this` inside the arrow function binds to outer environments `this`. Now the question is, what is that outer environment? Since you are `require`ing the file, we could argue that it is a `ModuleEnvironment`. But should CJS modules be treated as native ES6 modules?

A ModuleEnvironment has a `this` binding and it is defined as

> ##### [8.1.1.5.4 GetThisBinding ()](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-module-environment-records-getthisbinding)
> Return **undefined**.

So, from that perspective, you should actually get a runtime error, "cannot get x of undefined".

----

In Node, `this` inside a module refers to `module.exports`. However, you are assigning to `module.exports` and `this` still refers to the old `module.exports` value.

That leaves me to the conclusion that io.js' implementation is wrong, one way or the other.

**Comment by sebmck** [comment] 2015-01-21 19:14
This is expected behaviour. io.js doesn't ship with arrow functions enabled by default for good reason. You're going to bite yourself in the ass by enabling these features because their implementations aren't solid and spec compliant.

**Closed by sebmck** 2015-01-21 19:14 UTC

**Comment by fkling** [comment] 2015-01-21 19:41
@sebmck: What about enforcing that `this` is `undefined` in modules? Could be achieved through

```js
(function() {
  "use strict";
  // module code here
}());
```

Anything that uses `import` or `export` would be a module.

**Comment by sebmck** [comment] 2015-01-21 19:42
It's already enforced via `"use strict";`.

**Comment by fkling** [comment] 2015-01-21 19:45
That's not enough, because it depends on how the module loader evaluates the module code. E.g. it seems like Node is explicitly setting `this` to `module.exports`.

**Comment by sebmck** [comment] 2015-01-21 19:47
Oh right, I was only thinking of a browser environment. Wrapping all files in an IIFE is a pretty big change and one I'm not sure I'm willing to make.

**Comment by fkling** [comment] 2015-01-21 19:53
I understand. In that case, is there a list to keep track of small deviations like this? I know there is a caveats section on the webpage and http://kangax.github.io/compat-table/es6/, but neither of those seem to be the right place for this.

Or should I just create a new issue to keep track of this, even if it's not going to be changed in the near future?

**Comment by sebmck** [comment] 2015-01-21 19:54
A new issue would be great.

**Comment by sebmck** [comment] 2015-01-21 20:03
An alternate solution would be to just throw an error whenever we see any top level `this` expressions. It'd negate the need for a closure and would be more safe as under no circumstance would you reference `this` while it equaling `undefined`.

**Comment by fkling** [comment] 2015-01-21 20:17
@sebmck Filed as #562, maybe add your alternative solution there?
