### ISSUE TITLE
Spec Issue: super 

### ISSUE THREAD

**Issue by stefanpenner** [6to5/6to5#385] opened 2015-01-04 15:32 UTC
`super()` within non-constructor method works, but should (unfortunately) not.

```js
class Foo() {
  name() {
    return 'Foo';
  }  
}

class Bar() {
  name() {
    return super(); // should throw, as it is only to be used in the constructor
  }

  name() {
    return super.name(); // will work
  }
}
```

6to5 emits the following for both `super()` and `super.name()`

```js
 Foo.prototype.name = function () {
    _Bar.prototype.name.call(this);
  };
```

**Comment by sebmck** [comment] 2015-01-04 15:37
Just did some quick testing, [Traceur](https://google.github.io/traceur-compiler/demo/repl.html#class%20Bar%20%7B%0A%20%20bar()%20%7B%0A%20%20%20%20super()%3B%0A%20%20%7D%0A%7D%0A%0Avar%20bar%20%3D%20new%20Bar%3B%0Abar.bar()%3B) and Chrome Canary support it:

![screen shot 2015-01-05 at 2 37 56 am](https://cloud.githubusercontent.com/assets/853712/5606433/bdbbb49c-9483-11e4-88b5-3534b8293534.png)

I'll have to check the spec.

**Comment by stefanpenner** [comment] 2015-01-04 15:43
http://jsbin.com/zuzuzohiwe/1/edit?js,console seems to demonstrate failure. I am fairly confident this is the case, as it was the theme of a heated twitter discussion several weeks ago. (Unfortunately google search fails me)

**Comment by stefanpenner** [comment] 2015-01-04 15:44
found it: https://twitter.com/wycats/status/544553184396836864

**Comment by sebmck** [comment] 2015-01-04 15:46
Ah right okay, it's a recent change. I'm unsure if this check should be done at the parser or transformation level.

**Comment by stefanpenner** [comment] 2015-01-04 15:48
I would be favor of a parse-time failure if that isn't to aggressive.

**Comment by fkling** [comment] 2015-01-04 17:19
Yes, `super()` inside a class method (and outside `constructor`) has to be a parse error. See rev 30, 14.5.1

> ClassElement : MethodDefinition  
- It is a Syntax Error if PropName of MethodDefinition is not "constructor" and HasDirectSuper(MethodDefinition) is true.

**Comment by thejameskyle** [comment] 2015-01-04 18:22
While most spec-compliance related changes should go out immediately, I'm certain that 6to5 users are already doing this and I don't want to break their code suddenly.

I'm not sure how we should address these kinds of changes in semver.

@6to5/maintainers thoughts?

**Comment by stefanpenner** [comment] 2015-01-04 18:36
It depends on your semver tolerance. Bugfixes, or defining previously undefined behavior sometimes fall into this gray area.

I would personally not hesitate breaking at a patch or point release if it involves defining previous undefined behavior. Unfortunately, as I suspect this was previously defined, and now has change it should require a bump.

**Comment by thejameskyle** [comment] 2015-01-04 18:59
I'm thinking that it might be a good idea to put these kinds of changes, ones that are breaking to previous versions of the spec (which shouldn't happen very often anymore), in minor releases, so that people who need their code not to break can restrict it to patch releases.

**Comment by stefanpenner** [comment] 2015-01-04 19:07
> in minor releases, so that people who need their code not to break can restrict it to patch releases.

+1

Also, it might be good to annotate breaking changes clearly in the changelog

2.6.0
------

* **[Breaking change]** something something super
* something else non-breaking

**Comment by thejameskyle** [comment] 2015-01-04 19:16
It'd be good to tag changes (`[New Feature]`, `[Breaking Change]`, `[Bug Fix]`) in general, but let's take that conversation elsewhere.

**Comment by eventualbuddha** [comment] 2015-01-04 19:26
I too vote for point release with clear changelog annotation. I've certainly been using bare `super()` in my code, despite WebStorm complaining about it since before they changed the spec! Heh.

**Comment by sebmck** [comment] 2015-01-04 22:20
I'm completely in support of better changelog annotation. Anyone mind adding a scheme to the top of `CHANGELOG.md`?

**Comment by thejameskyle** [comment] 2015-01-04 22:22
@sebmck Sure I'll add it, any other suggestions other than these?
- `[Bug Fix]`
- `[New Feature]`
- `[Breaking Change]`
- `[Documentation]`

**Comment by sebmck** [comment] 2015-01-04 22:31
@thejameskyle I think a "Spec Compliancy" label would be a really good idea. Even though 99% of them would go under the "Breaking Change" I still think it'd be good for transparency.

**Comment by sebmck** [comment] 2015-01-08 01:54
This change seems to have been confirmed. Anybody have an issues if I make this illegal?

**Comment by thejameskyle** [comment] 2015-01-21 21:26
Looks like this was fixed in https://github.com/6to5/6to5/commit/f2a432531ef1908a18784999f3bc0d0c124a944e.

**Closed by thejameskyle** 2015-01-21 21:26 UTC
Labels: parser, spec compliancy

**Comment by sebmck** [comment] 2015-01-28 02:55
Bare super inside non-constructor methods now errors as of 3.0.0

**Comment by stefanpenner** [comment] 2015-01-28 03:02
yay
