### ISSUE TITLE
Add ability to configure compiling for specific browsers/environments.

### ISSUE THREAD

**Issue by neformal13** [6to5/6to5#731] opened 2015-02-09 14:13 UTC
Maybe it does not cover main idea of 6to5 compiler, but it will be great if we will have ability to specify for which environment we wrote our application.
For example, I wrote some modern application of latest version of Firefox and Google Chrome, but according this table http://kangax.github.io/compat-table/es6/, we actually have native support for a lot of things from ES6 in these browsers.
This means that it is not necessary to compile a lot of things into ES5.

I like approach from [autoprefixer](https://github.com/postcss/autoprefixer#browsers)
where we can configure our build like ```last 2 versions``` or ```> 5%.```

**Comment by sebmck** [comment] 2015-02-09 14:15
Duplicate of #631.

**Closed by sebmck** 2015-02-09 14:15 UTC
