### ISSUE TITLE
REPL: Some links don't quite work in Firefox

### ISSUE THREAD

**Issue by webbedspace** [6to5/6to5#542] opened 2015-01-20 02:27 UTC
Opening [this link](6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&code=let%20foo%20%3D%20Symbol(%27foo%27)%3B%0Aconsole.log(String(foo)%3D%3D%3D%27Symbol(foo)%27)%3B%0Atry%20%7B%0A%20%20console.log(foo%20%2B%20%22%22)%3B%0A%7D%20catch%20(e)%20%7B%7D%0Atry%20%7B%0A%20%20console.log(foo%20%2B%200)%3B%0A%7D%20catch%20(e)%20%7B%7D) in Firefox only produces `let foo` in the left pane.

**Comment by sebmck** [comment] 2015-01-20 02:29
Duplicate of 6to5/6to5.github.io#61

**Closed by sebmck** 2015-01-20 02:29 UTC
