### ISSUE TITLE
Read configuration from .6to5 file? 

### ISSUE THREAD

**Issue by assaf** [6to5/6to5#622] opened 2015-01-28 18:30 UTC
One project I'm working on has three different places where I need to pass options to 6to5. There's the test suite that runs ES6 code with `6to5/register`, the Gulpfile that builds ES5 code that I can `npm publish`, and the REPL.

Keeping all three in sync is not easy, especially when configurations change (e.g. just released 3.0). What about having all three reading their configuration from the same file?

**Comment by AluisioASG** [comment] 2015-01-28 18:40
Duplicate of #351

**Closed by AluisioASG** 2015-01-28 18:40 UTC
