### ISSUE TITLE
destructuring assignment returns wrong value in REPL

### ISSUE THREAD

**Issue by tolmasky** [6to5/6to5#502] opened 2015-01-15 06:09 UTC
Not sure, but I believe this descrepency shouldn't exist:

If I type the following in the REPL:

> [x,y] = [1,2]

I get this as a result:

> 2

However, if I type:

> z = ([x,y] = [1,2])

I get this:

> [1,2]

I *believe* the second is correct. This could potentially create issue with further code transformations on top of this (as I think the = () one should be the mutation that is always used).

**Comment by sebmck** [comment] 2015-01-15 06:15
I should probably add a warning when starting the REPL about this kind of issue. Basically it's not transformed into the expected because it's unnecessary in the context of a script since it doesn't have to return the exact result of the original expression. There's not really anything that can be done about this. Stuff like constants will also break in the REPL since it requires access to the entire script for static analysis.

**Comment by sebmck** [comment] 2015-01-15 06:20
Actually there's possibly a way to do this. I can check whether or not the to be evaluated result is an expression/expression statement and wrap it in some other non-standard node to trigger the expression handling of all transformers. I'll have a look when I can and I'll keep you posted.

**Comment by tolmasky** [comment] 2015-01-15 06:34
Yeah I was about to say that unlike the const example this *should* be possible (for example, once this is native, the node repl will definitely return the right thing, unlike const which it still won't be able to handle). 

That being said, I think it should simply *always* be transforming the equal expression to the temp form you get when wrapping it in an additional ='s. The = operator is supposed to return the right hand side always, so there's no reason not to (aside from perf or something?). Just to list an example off the top of my head, the following in real es6 land:

y = eval("[a,b]=[1,2]")

should leave y === [1,2] (the same as had you done y = eval("z = [1,2]").

However, with the current setup:

eval = (x) => eval(to5(x))
y = eval("[a,b]=[1,2]")

will have y === 2 (in other words, its not necessarily just a node-repo issue).

I think the expression itself (which = is) should *always* evaluate to the temp form.

**Comment by sebmck** [comment] 2015-01-15 06:36
@tolmasky It doesn't evaluate to the temp form on just:

```javascript
[a, b] = [1, 2];
```

because it's inside an expression statement where we don't really need to evaluate it as an expression. Otherwise we'll have to output useless nodes and code.

This however brings up the possible inclusion of an `expression` option that treats single expression statements as normal expressions that have consequences.

**Comment by tolmasky** [comment] 2015-01-15 07:43
I'm not sure if the single expression thing would be enough, since eval("[a,b] = [1,2]; [c,d] = [3,4]") should also return [3,4] (as should repl "> [a,b]=1,2]; [c,d]=[3,4]"

My apologies as I am not familiar with the internal workings of 6to5, but just doing some simple tests it seems that in the simple cases  (2 elements in the restructured array) the node counts are very comparable (4 node "slowdown"), and it actually *improves* with each additional argument, breaking even at 6 and afterward the expression format beating the statement format by 1 node per additional element:

2-elements
statement: 90
expression: 94

3-elements
statement: 97
expression: 100

6-elements
statement: 118
expression: 118

14-elements
statement: 174
expression: 166

I put the code up that does these tests here: https://github.com/tolmasky/expression-comparison . To come up with the generated code, I just ran "[a,b]=[1,2]" through 6to5 in the playground. Then I did the same for "5, [a,b]=[1,2]" and removed the "5," from the generated result.

Perhaps I'm missing some corner cases (or other slowdowns), but it seems that for most cases it actually generates less useless nodes and code, and would have the additional benefit of just being one code path to go through. Even if we were to say "on average people only destructure with 4 or less elements", we're talking about an average of 3 extra nodes.

**Comment by sebmck** [comment] 2015-01-15 07:48
Basically, the destructuring transformer (and most other transformers for this matter) will change their output on transforming expressions if the expression is a direct child of an expression statement. This is because this code has no consequence as nothing is expecting to get it's return value. For this reason a reference back to `[1, 2]` is simply left out of the returning nodes.

What I'm proposing is to change the very last expression statement in the parsed code to a different node type that's not expression statement to remove over this behaviour.

**Comment by tolmasky** [comment] 2015-01-15 07:54
Ah (now we're getting at something very similar to what I'm working on where I actually reached this problem). At least in my own code, I found it easier to treat all expressions the same, because if not finding the "last expression" can be somewhat complicated. For example, in this code there are two "last expressions":

if (val) [a,b]=[1,2]; else [a,b] = [3,4];

(In node repl "if (false) x=9; else x=10" returns 10 per eval rules of returning value of "last expression").

Maybe the way 6to5 is written its easy to reason about all the possible nested potential last expressions (every case inside every last switch inside every top level if....), but when I was traversing my nodes for a similar but unrelated task it seemed easier to just hit up every expression.

**Comment by tolmasky** [comment] 2015-01-15 08:00
(Also, given the tests I ran (which again may admittedly very well not cover all the cases), it seems like it may potentially be a win in node-count (or at the very least not much of a loss) to just always generate the expression code.)

**Comment by sebmck** [comment] 2015-01-15 08:03
It's not really node count, it's more about how similar it is to the original code. We can transform code to something that's ugly as shit but still functions 100% but it's worth the effort to add in these edgecases.

A more simpler solution would be to just have an `expression` option or something similar in 6to5 that the REPL passes that makes the transformers forcibly output the result when in expression statements. Code output size wouldn't be an issue since that code wouldn't be visible to the user anyway.

**Comment by oriSomething** [comment] 2015-01-20 12:19
in a relating issue. it seems to me like a bug. a small one though.

![6to5](https://cloud.githubusercontent.com/assets/2685242/5816996/573f7bc6-a0af-11e4-9888-0f27978f9fc2.png)

**Comment by sebmck** [comment] 2015-01-20 12:20
@oriSomething Not a bug. Destructuring declarations must have an initializer.

**Comment by oriSomething** [comment] 2015-01-20 12:27
@sebmck but it weird that it did compiled. it suppose to throw an error during compilation. because even in a browser that supports ES6 (destructuring declarations) it wouldn't pass.
the completion means that this syntax is valid which is not:
```js
var s = 1;
var {s};
```

**Comment by sebmck** [comment] 2015-01-20 12:28
@oriSomething It does fail to compile though which is expected behaviour?

**Comment by oriSomething** [comment] 2015-01-20 12:35
@sebmck it shows that the error is only runtime.

but forget about it. there is something in FF behavior that doesn't align with the specs.
so what i've said isn't really relevant

**Comment by sebmck** [comment] 2015-01-23 13:21
Fixed in 3.0.0, thanks!

**Closed by sebmck** 2015-01-23 13:21 UTC
Labels: bug
