### ISSUE TITLE
[Regression] False positive scoping error with imports

### ISSUE THREAD

**Issue by andreypopp** [6to5/6to5#773] opened 2015-02-13 07:18 UTC
The code:
```
import {Dispatcher as BaseDispacther} from 'flux';

class Dispatcher extends BaseDispacther {

}
```
Results in:
```
/Users/andreypopp/Workspace/gang/node_modules/6to5/bin/6to5/util.js:35
      throw e;
            ^
TypeError: ./test.js: Line 1: Duplicate declaration "Dispatcher"
> 1  | import {Dispatcher as BaseDispacther} from 'flux';
     |         ^
  2  | 
  3  | class Dispatcher extends BaseDispacther {
  4  | 
    at File.errorWithNode (~/6to5/lib/6to5/transformation/file.js:333:13)
    at Scope.checkBlockScopedCollisions (~/6to5/lib/6to5/traversal/scope.js:145:21)
    at Scope.registerBinding (~/6to5/lib/6to5/traversal/scope.js:299:10)
    at Scope.registerDeclaration (~/6to5/lib/6to5/traversal/scope.js:277:10)
    at TraversalPath.functionVariableVisitor.enter (~/6to5/lib/6to5/traversal/scope.js:341:44)
    at TraversalPath.call (~/6to5/lib/6to5/traversal/path.js:115:24)
    at TraversalPath.visit (~/6to5/lib/6to5/traversal/path.js:136:8)
    at TraversalContext.visitNode (~/6to5/lib/6to5/traversal/context.js:24:20)
    at TraversalContext.visit (~/6to5/lib/6to5/traversal/context.js:41:26)
    at Function.traverse.node (~/6to5/lib/6to5/traversal/index.js:38:17)
```

**Comment by sebmck** [comment] 2015-02-13 07:20
Duplicate of #762, I'll push out a release soon.

**Closed by sebmck** 2015-02-13 07:20 UTC
