### ISSUE TITLE
Definable compilation targets

### ISSUE THREAD

**Issue by eemeli** [6to5/6to5#745] opened 2015-02-10 21:15 UTC
I'm putting together a build system for typed JavaScript, and would like to combine the ES6+ support of 6to5 with the type checking of Flow. Therefore, I'd be interested in a minimal set of 6to5 transforms that would produce Flow-compatible code. As that's a moving target (as per facebook/flow#62), this could make sense as a 6to5 `--target` CLI option, rather than a requirement to define a possibly extensive set of white- and blacklists of transforms.

And of course, if Flow makes sense as a target, so do other platforms as well, such as the Espree of #581. Is this something that could be in the scope of 6to5?

**Comment by sebmck** [comment] 2015-02-10 21:24
The issue is having a moving target, it'd be a big effort to constantly have all these lists maintained and updated whenever something is changed upstream. #631 may be partially relevant, it's only possible because there are other databases with feature support maintained elsewhere.

**Comment by sebmck** [comment] 2015-02-11 02:27
Merged into #631.

**Closed by sebmck** 2015-02-11 02:27 UTC

**Comment by balupton** [comment] 2015-03-21 17:17
So what is the equivalent of this with the new architecture? I can't seem to find out what it maps to.

**Comment by sebmck** [comment] 2015-03-22 02:57
@balupton Nothing yet, I preemptively consolidated a bunch of issues. I'll reopen #631 to track progress.
