### ISSUE TITLE
Option for disable _interopRequire

### ISSUE THREAD

**Issue by nkt** [6to5/6to5#561] opened 2015-01-21 16:31 UTC
There is no option for this.
Actually some of modules define `default` property in `exports`.
https://github.com/expressjs/morgan/blob/master/index.js#L191
```js
exports.format = function(name, fmt){
  exports[name] = fmt;
  return this;
};
exports.format('default', ...);
```

**Comment by lukescott** [comment] 2015-01-21 18:25
I noticed that only the `import` statements are wrapped in _interopRequire. If you use a regular `require()` it doesn't wrap it, or at least it was in my case.

I ended up using [esperanto](https://github.com/esperantojs/esperanto) to pre-process my es6 code, which converts it can convert it to umd/commonjs/amd. From there you can apply 6to5. I used esperanto's bundler to eliminate the require's completely instead of using something like browserify.

**Comment by sebmck** [comment] 2015-01-21 19:15
Duplicate of #493

**Closed by sebmck** 2015-01-21 19:15 UTC
