### ISSUE TITLE
IE 10 does not properly inherit constructor

### ISSUE THREAD

**Issue by crob611** [6to5/6to5#573] opened 2015-01-22 22:41 UTC
Not sure if this is supposed to be supported or not, but we ran into and thought we would make you aware.  

If a subclass does not define a constructor, it does not have the expected functionality in IE10.  

```
class A {
  constructor(data) {
    this.data = data
  }
}

class B extends A {
}

var a = new A('I am A');
var b = new B('I am B');
```

In Chrome, Firefox, IE11, `b.data` is `I am B`. 
In IE10, `b.data` is `undefined`

JsFiddle: http://jsfiddle.net/c8r2rcqo/
JsFiddle giving B a constructor that just calls `super`. This was our workaround: http://jsfiddle.net/c8r2rcqo/2

**Comment by sebmck** [comment] 2015-01-22 22:46
Weird, the current super behaviour was introduced with #408. @eventualbuddha Any ideas?

A possible fix that you may find preferable is [loose mode](http://6to5.org/docs/usage/loose/#classes). It'll make 6to5 generate cleaner and code that executes faster with the addition of a few extremely edgecase caveats.

**Comment by sebmck** [comment] 2015-01-25 14:11
Investigated this and `Object.getPrototypeOf` isn't returning the correct result. Not sure why this is, may be an issue with the current `_inherits` behaviour.

**Comment by sebmck** [comment] 2015-01-26 11:22
```javascript
class A {}
class B extends A {}

new B instanceof A; // true
```

That works fine but `Object.getPrototypeOf` on `B` doesn't work as expected. Looks like an IE bug and I'm not sure if there's any way to fix it.

**Comment by zloirock** [comment] 2015-01-26 12:30
@sebmck IE10- not support `__proto__`, only 1  way:
```javascript
var C = (function (P) {
  function C() {
    var _tmp = '__proto__' in Object.prototype ? Object.getPrototypeOf(C) : P;
    if(_tmp !== null)_tmp.apply(this, arguments);
  }

  _inherits(C, P);

  return C;
})(P);
```
but it's ugly.

**Comment by sebmck** [comment] 2015-01-26 12:35
@zloirock [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf) says >=IE9 supports `Object.getPrototypeOf`.

**Comment by zloirock** [comment] 2015-01-26 12:38
@sebmck 6to5 inherits constructor using `__proto__`, IE10- not support `__proto__`. `Object.getPrototypeOf`  is not the problem.

**Comment by sebmck** [comment] 2015-01-26 12:39
@zloirock It only uses `__proto__` to inherit static properties. In this case `Object.getPrototypeOf` isn't resolving to the correct constructor so the super isn't being called at all.

**Comment by zloirock** [comment] 2015-01-26 12:45
@sebmck static properties *with constructor* :) And we get the super constructor similarly.

**Comment by sebmck** [comment] 2015-01-26 12:49
@zloirock See [this](http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&=&code=class%20A%20%7B%7D%0A%0Aclass%20B%20extends%20A%20%7B%7D).

```javascript
if (Object.getPrototypeOf(B) !== null) {
  Object.getPrototypeOf(B).apply(this, arguments);
}
```

is used to get the super constructor.

**Comment by zloirock** [comment] 2015-01-26 12:52
@sebmck In IE10 we have:
```javascript
class B extends A {}
// =>
if (Object.getPrototypeOf(B) !== null) { // <- Function.prototype instead of A
  Object.getPrototypeOf(B).apply(this, arguments); // <- call Function.prototype === call empty function
}
```

**Comment by sebmck** [comment] 2015-01-26 12:53
@zloirock Yep, that's the bug that this issue is reporting.

**Comment by zloirock** [comment] 2015-01-26 13:00
I just showed that the problem is not in `Object.getPrototypeOf`, it's works correctly, problem in  `__proto__` in `_inherits` - we can not get the constructor did not inherits it.The only way to fix - fallback for browsers without `__proto__'.

**Comment by sebmck** [comment] 2015-01-26 13:02
@zloirock Oh right, duh. I could use some sleep. I'll just add this to the caveats and encourage the use of [loose mode](http://6to5.org/docs/usage/loose/). Thanks!

**Closed by sebmck** 2015-01-26 13:02 UTC
Labels: bug

**Comment by robmadole** [comment] 2015-02-05 16:31
It looks like this has been fixed with a recent version. I did a quick test using the "Try it out" feature of the 6to5 site in IE10 and the constructor is being called from an inherited class. Just wanted to mention that for anyone else who finds this ticket.
